# Generated by Django 5.2.8 on 2026-08-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
