# Generated by Django 5.2.8 on 2026-08-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('image_url', models.TextField()),
                ('read_time', models.CharField(default='5 min read', max_length=50)),
                ('author', models.CharField(default='Explore Getaway Team', max_length=100)),
                ('published_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
