# Generated by Django 5.2.8 on 2026-08-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticle',
            name='read_time',
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='author',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
