# Generated by Django 5.2.8 on 2026-08-18 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('duration_nights', models.PositiveIntegerField(default=1)),
                ('duration_days', models.PositiveIntegerField(default=2)),
                ('location_summary', models.CharField(max_length=255)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.FloatField(default=4.5)),
                ('reviews_count', models.PositiveIntegerField(default=10)),
                ('badge_text', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.TextField()),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('description', models.TextField()),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('inclusions', models.JSONField(blank=True, default=list)),
                ('exclusions', models.JSONField(blank=True, default=list)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='destinations.category')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='destinations.destination')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='packages.tourpackage')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
