# Generated by Django 5.2.8 on 2026-08-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_tourpackage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='cancellation_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='day_wise_itinerary',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='tour_overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='upcoming_departures',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
