# Generated by Django 5.2.8 on 2026-08-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_tourpackage_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='description',
        ),
    ]
