# Generated by Django 5.2.8 on 2026-08-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_remove_tourpackage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
