# Generated by Django 5.2.8 on 2026-08-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_tourpackage_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='double_sharing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='triple_sharing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
