# Generated by Django 5.2.8 on 2026-08-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_tourpackage_double_sharing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='child_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
