# Generated by Django 5.2.8 on 2026-08-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_tourpackage_child_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='best_for',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
