# Generated by Django 5.2.8 on 2026-08-18 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('packages', '0002_alter_tourpackage_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
