# Generated by Django 5.2.8 on 2026-08-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_popular',
        ),
        migrations.AddField(
            model_name='category',
            name='display_label',
            field=models.CharField(choices=[('for_everyone', 'For Everyone'), ('for_two', 'For Two'), ('for_families', 'For Families'), ('for_groups', 'For Groups'), ('for_adventure', 'For Adventure'), ('for_relaxation', 'For Relaxation')], default='for_everyone', max_length=30),
        ),
    ]
