# Generated by Django 5.2.8 on 2026-08-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_is_popular_category_display_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display_label',
            field=models.CharField(choices=[('for_everyone', 'For Everyone'), ('for_solo_travelers', 'For Solo Travelers'), ('for_families', 'For Families'), ('for_groups', 'For Groups'), ('for_friends', 'For Friends'), ('for_couples', 'For Couples'), ('for_relaxation', 'For Relaxation')], default='for_everyone', max_length=30),
        ),
    ]
